sonata-nfv/tng-sdk-package

- README.md
- pytest.ini
- requirements.txt
- setup.py
- src/tngsdk/__init__.py
- src/tngsdk/package/__init__.py
- src/tngsdk/package/tests/__init__.py
- src/tngsdk/package/tests/test_unit_package.py
> Prepared initial seed code.

- .gitignore
- Jenkinsfile
- pipeline/build/build.sh
- pipeline/checkstyle/check.sh
- pipeline/unittest/test.sh
> Enabeling CI integration

- README.md
> Test multibranch pipeline

- .dockerignore
- .gitignore
- Dockerfile
- pipeline/build/build.sh
- pipeline/checkstyle/check.sh
- pipeline/unittest/test.sh
> Enabled unittest and checkstyle stages.

- src/tngsdk/package/cli.py
- src/tngsdk/package/pkgmgm.py
- src/tngsdk/package/rest.py
- src/tngsdk/package/tests/test_unit_pkgmgm.py
> Added basic CLI interface. Closes #6.

- pipeline/checkstyle/check.sh
- requirements.txt
- src/tngsdk/package/__init__.py
- src/tngsdk/package/rest.py
- src/tngsdk/package/tests/test_unit_pkgmgm.py
- src/tngsdk/package/tests/test_unit_rest.py
> Added basic REST interface endpoint. Closes #7.

- Dockerfile
Docker container is deployed. Closes #8.
> Automatically run packager in service mode when

- requirements.txt
- src/tngsdk/package/__init__.py
- src/tngsdk/package/cli.py
- src/tngsdk/package/packager.py
- src/tngsdk/package/rest.py
- src/tngsdk/package/tests/test_unit_packager.py
- src/tngsdk/package/tests/test_unit_rest.py
> Redesign and moved to flask-restplus lib.

- misc/callback_mock.py
- src/tngsdk/package/rest.py
> Changed field names in callback request.

- pipeline_local.sh
- src/tngsdk/package/tests/test_unit_rest.py
> Improved REST unittests

- misc/callback_mock.py
- requirements.txt
- src/tngsdk/package/rest.py
- src/tngsdk/package/tests/test_unit_rest.py
Imporved unittest of callback mechanism.
> Added package_process_uuid to callback payload.

- Jenkinsfile
- pipeline/promote/promote-int.sh
- pipeline/publish/publish.sh
> CI: Implemented conatiner publish stage in pipeline

- Dockerfile
- pipeline/checkstyle/check.sh
- src/tngsdk/package/packager.py
- src/tngsdk/package/tests/test_unit_packager.py
- src/tngsdk/package/tests/test_unit_packager_tango.py
> Added functionality to parese TOSCA.meta and ETSI manifest metadata.

- Jenkinsfile
- misc/callback_mock.py
- src/tngsdk/package/rest.py
- src/tngsdk/package/storage.py
> Fix: Preserver package file name during unpacking. Closes #73

- src/tngsdk/package/storage.py
and switched to a concept of annotated PDs.
Closes #75
> Removed mapping endpoint usage of tng-cat-backend

- Dockerfile
- src/tngsdk/package/packager.py
- src/tngsdk/package/rest.py
- src/tngsdk/package/storage.py
- src/tngsdk/package/tests/fixtures.py
- src/tngsdk/package/tests/test_unit_packager_tango.py
- src/tngsdk/package/tests/test_unit_storage_tango.py
> Much more unit tests and more configuration options.

- src/tngsdk/package/rest.py
> Fix: ENV variable wrong parsing

- .gitignore
- README.md
- src/tngsdk/package/packager.py
- src/tngsdk/package/tests/test_unit_packager_tango.py
> Finalized CLI packaging

- src/tngsdk/package/__init__.py
- src/tngsdk/package/cli.py
- src/tngsdk/package/packager.py
Signed-off-by: peuster  <manuel.peuster@uni-paderborn.de>
> Better output in CLI mode. Closes: #63

- Jenkinsfile
> Changed CI scripts for int. promotion

- src/tngsdk/package/packager.py
> Fix: Make tool more robust in older environments.

- README.md
> Pip install documentation

- src/tngsdk/package/rest.py
> Added more debug output to print file size after upload.

- src/tngsdk/package/packager.py
- src/tngsdk/package/storage/__init__.py
- src/tngsdk/package/storage/tngcat.py
- src/tngsdk/package/tests/test_unit_storage_tngcat.py
> Added check if package is already present in tng-cat to abort uploading

- README.md
- src/tngsdk/package/rest.py
> Fix: store_skip was not passed in service mode. Updated readme.

- Jenkinsfile
> removed vnv-int from CI (env doesn't exist yet)

- README.md
> Improved README.md for release.

- Jenkinsfile
- pipeline_local.sh
- src/tngsdk/package/tests/test_unit_python_api.py
> Added Python API entry point to call packager from tng-sdk-bench

- src/tngsdk/package/cli.py
> Adding --quiet flag. Closes #121

- Jenkinsfile
> Re-enabled container publication in CI pipeline.

- pipeline/build/build.sh
- src/tngsdk/package/cli.py
> Fix: Validator integration

- Dockerfile
> Disabled validator for unpackaging

- src/tngsdk/package/tests/test_unit_rest.py
> Fix: Test may fail because of slow validation. Closes #148

- src/tngsdk/package/validator.py
> Activating topology validation as default

- Dockerfile
> Disableing validator for demos

- Dockerfile
- src/tngsdk/package/validator.py
> Re-activating the validator. Also increased loglevel to simplify

- src/tngsdk/package/validator.py
> Re-trigger new build

- Dockerfile
- src/tngsdk/package/tests/test_unit_rest.py
> Disable Validator

- src/tngsdk/package/packager.py
> Fix: Correctly detect OSM/ONAP descriptors

- Dockerfile
> Re-activating Validator

- src/tngsdk/package/storage/tngcat.py
> Fix: Small glitch in tng-cat parameters

- src/tngsdk/package/cli.py
- src/tngsdk/package/packager.py
- src/tngsdk/package/tests/test_unit_packager.py
Changes in cli.py(Added argument), packager.py(Functions autoversion(), storeautoversion()), test_unit_packager.
> Autoversion

- src/tngsdk/package/storage/__init__.py
- src/tngsdk/package/storage/tngcat.py
> Support for OSM in tng-cat storage backend. Closes #167

- Dockerfile
> Activating validator

- src/tngsdk/package/__init__.py
> Early fail if a user runs the tool on Python 2

- src/tngsdk/package/rest.py
- src/tngsdk/package/tests/test_unit_rest.py
changed to relative download link, because url_for() needs context to create an url
> Fixed Callback for creating package via REST interface

- Dockerfile
> Disabeling Validator

- src/tngsdk/package/packager/packager.py
- src/tngsdk/package/packager/tango_packager.py
> Skip validation using ENV var

- MANIFEST.in
- README.md
- setup.py
> Improved packaging for Pypi

- Jenkinsfile
> jenkinsfile: no deployment for rel5

- setup.py
> Increased version to 5.1
